/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZonesRouteImport } from './routes/zones'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SatelliteRouteImport } from './routes/satellite'
import { Route as MotorRouteImport } from './routes/motor'
import { Route as MapRouteImport } from './routes/map'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as HardwareRouteImport } from './routes/hardware'
import { Route as GpsRouteImport } from './routes/gps'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicTelemetryRouteImport } from './routes/api/public/telemetry'
import { Route as ApiPublicCommandsRouteImport } from './routes/api/public/commands'

const ZonesRoute = ZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SatelliteRoute = SatelliteRouteImport.update({
  id: '/satellite',
  path: '/satellite',
  getParentRoute: () => rootRouteImport,
} as any)
const MotorRoute = MotorRouteImport.update({
  id: '/motor',
  path: '/motor',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const HardwareRoute = HardwareRouteImport.update({
  id: '/hardware',
  path: '/hardware',
  getParentRoute: () => rootRouteImport,
} as any)
const GpsRoute = GpsRouteImport.update({
  id: '/gps',
  path: '/gps',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelemetryRoute = ApiPublicTelemetryRouteImport.update({
  id: '/api/public/telemetry',
  path: '/api/public/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCommandsRoute = ApiPublicCommandsRouteImport.update({
  id: '/api/public/commands',
  path: '/api/public/commands',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/devices': typeof DevicesRoute
  '/forecast': typeof ForecastRoute
  '/gps': typeof GpsRoute
  '/hardware': typeof HardwareRoute
  '/history': typeof HistoryRoute
  '/map': typeof MapRoute
  '/motor': typeof MotorRoute
  '/satellite': typeof SatelliteRoute
  '/settings': typeof SettingsRoute
  '/zones': typeof ZonesRoute
  '/api/public/commands': typeof ApiPublicCommandsRoute
  '/api/public/telemetry': typeof ApiPublicTelemetryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/devices': typeof DevicesRoute
  '/forecast': typeof ForecastRoute
  '/gps': typeof GpsRoute
  '/hardware': typeof HardwareRoute
  '/history': typeof HistoryRoute
  '/map': typeof MapRoute
  '/motor': typeof MotorRoute
  '/satellite': typeof SatelliteRoute
  '/settings': typeof SettingsRoute
  '/zones': typeof ZonesRoute
  '/api/public/commands': typeof ApiPublicCommandsRoute
  '/api/public/telemetry': typeof ApiPublicTelemetryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/devices': typeof DevicesRoute
  '/forecast': typeof ForecastRoute
  '/gps': typeof GpsRoute
  '/hardware': typeof HardwareRoute
  '/history': typeof HistoryRoute
  '/map': typeof MapRoute
  '/motor': typeof MotorRoute
  '/satellite': typeof SatelliteRoute
  '/settings': typeof SettingsRoute
  '/zones': typeof ZonesRoute
  '/api/public/commands': typeof ApiPublicCommandsRoute
  '/api/public/telemetry': typeof ApiPublicTelemetryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/alerts'
    | '/analytics'
    | '/app'
    | '/auth'
    | '/billing'
    | '/devices'
    | '/forecast'
    | '/gps'
    | '/hardware'
    | '/history'
    | '/map'
    | '/motor'
    | '/satellite'
    | '/settings'
    | '/zones'
    | '/api/public/commands'
    | '/api/public/telemetry'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/alerts'
    | '/analytics'
    | '/app'
    | '/auth'
    | '/billing'
    | '/devices'
    | '/forecast'
    | '/gps'
    | '/hardware'
    | '/history'
    | '/map'
    | '/motor'
    | '/satellite'
    | '/settings'
    | '/zones'
    | '/api/public/commands'
    | '/api/public/telemetry'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/alerts'
    | '/analytics'
    | '/app'
    | '/auth'
    | '/billing'
    | '/devices'
    | '/forecast'
    | '/gps'
    | '/hardware'
    | '/history'
    | '/map'
    | '/motor'
    | '/satellite'
    | '/settings'
    | '/zones'
    | '/api/public/commands'
    | '/api/public/telemetry'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  AlertsRoute: typeof AlertsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AppRoute: typeof AppRoute
  AuthRoute: typeof AuthRoute
  BillingRoute: typeof BillingRoute
  DevicesRoute: typeof DevicesRoute
  ForecastRoute: typeof ForecastRoute
  GpsRoute: typeof GpsRoute
  HardwareRoute: typeof HardwareRoute
  HistoryRoute: typeof HistoryRoute
  MapRoute: typeof MapRoute
  MotorRoute: typeof MotorRoute
  SatelliteRoute: typeof SatelliteRoute
  SettingsRoute: typeof SettingsRoute
  ZonesRoute: typeof ZonesRoute
  ApiPublicCommandsRoute: typeof ApiPublicCommandsRoute
  ApiPublicTelemetryRoute: typeof ApiPublicTelemetryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zones': {
      id: '/zones'
      path: '/zones'
      fullPath: '/zones'
      preLoaderRoute: typeof ZonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/satellite': {
      id: '/satellite'
      path: '/satellite'
      fullPath: '/satellite'
      preLoaderRoute: typeof SatelliteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motor': {
      id: '/motor'
      path: '/motor'
      fullPath: '/motor'
      preLoaderRoute: typeof MotorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hardware': {
      id: '/hardware'
      path: '/hardware'
      fullPath: '/hardware'
      preLoaderRoute: typeof HardwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gps': {
      id: '/gps'
      path: '/gps'
      fullPath: '/gps'
      preLoaderRoute: typeof GpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telemetry': {
      id: '/api/public/telemetry'
      path: '/api/public/telemetry'
      fullPath: '/api/public/telemetry'
      preLoaderRoute: typeof ApiPublicTelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/commands': {
      id: '/api/public/commands'
      path: '/api/public/commands'
      fullPath: '/api/public/commands'
      preLoaderRoute: typeof ApiPublicCommandsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  AlertsRoute: AlertsRoute,
  AnalyticsRoute: AnalyticsRoute,
  AppRoute: AppRoute,
  AuthRoute: AuthRoute,
  BillingRoute: BillingRoute,
  DevicesRoute: DevicesRoute,
  ForecastRoute: ForecastRoute,
  GpsRoute: GpsRoute,
  HardwareRoute: HardwareRoute,
  HistoryRoute: HistoryRoute,
  MapRoute: MapRoute,
  MotorRoute: MotorRoute,
  SatelliteRoute: SatelliteRoute,
  SettingsRoute: SettingsRoute,
  ZonesRoute: ZonesRoute,
  ApiPublicCommandsRoute: ApiPublicCommandsRoute,
  ApiPublicTelemetryRoute: ApiPublicTelemetryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
